name: Klonla ve Yeni Repoya Aktar

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Kaynak repoyu mirror olarak klonla
      run: |
        git clone --mirror https://github.com/GitLatte/repos.git

    - name: gh CLI yükle
      run: |
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Yeni repo oluştur
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo $GH_TOKEN | gh auth login --with-token
        gh repo create CkAcademy/repos-clone --public --confirm || echo "Repo zaten var"

    - name: İçeriği yeni repoya aktar
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd repos.git
        git remote set-url --push origin https://x-access-token:${GH_TOKEN}@github.com/CkAcademy/repos-clone.git
        git push --mirror
