name: Başka Depodan Dosya Aktarımı

on:
  workflow_dispatch:

jobs:
  copy-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Mevcut repoyu checkout et (push için yetkili)
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Kaynak repoyu klonla
      run: |
        git clone https://github.com/GitLatte/repos.git kaynak

    - name: Mevcut repodaki tüm dosyaları sil (.git ve .github hariç)
      run: |
        shopt -s extglob
        rm -rf !(kaynak|.git|.github)

    - name: Kaynak dosyalarını kopyala
      run: |
        cp -r kaynak/. .
        rm -rf kaynak

    - name: Değişiklikleri commit et ve pushla
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "GitLatte/repos deposundan dosya aktarımı" || echo "Değişiklik yok"
        git push origin HEAD:${GITHUB_REF#refs/heads/}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
