name: GitLatte/repos içeriğini kendi repoma aktar

on:
  workflow_dispatch:

jobs:
  copy-gitlatte-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Kendi repoyu çek
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: GitLatte/repos'u klonla
        run: git clone --depth=1 https://github.com/GitLatte/repos.git kaynak

      - name: Mevcut dosyaları sil (.git ve .github hariç)
        run: |
          shopt -s extglob
          rm -rf !(kaynak|.git|.github)

      - name: Kaynak içeriğini kopyala
        run: |
          cp -a kaynak/. .
          rm -rf kaynak

      - name: Commit ve force push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "GitLatte/repos içeriği aktarıldı (force sync)" || echo "No changes to commit"
          git push --force origin HEAD:main
